KhmerEmpireShop/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('products.urls')),
    path('', include('userprofile.urls')),
    path('', include('orders.urls')),
    path('', include('dashboard.urls')),
    path('', include('api.urls')),
    
    
    
    
    path('accounts/', include('allauth.urls')),
    
    
]

api/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from django.shortcuts import render 
from . import views
from django.conf import settings


urlpatterns = [
    path('api/products/', views.LaptopSpecListAPI.as_view(), name='products-api'),
    path('api/products/<slug:slug>/', views.ProductDetailBySlugAPI.as_view(), name='product-detail-api'),
    




    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *
from django.contrib import admin
from django.conf import settings 
from django.conf.urls.static import static
from home import views



app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    # path('base/', BaseView.as_view(), name='base'),
    path('', HomeAuth.as_view(), name='home_auth'),

    # authentication

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from django.shortcuts import render 
from . import views
from django.conf import settings

app_name = 'orders'

urlpatterns = [
    path('check-login-status/', views.CheckLoginStatusView.as_view(), name='check_login_status'),
    path('add-to-cart/<slug:slug>/',views. AddToCartView.as_view(), name='add_to_cart'),
    path('cart/', views.CartDetailView.as_view(), name='cart_detail'),
    path('clear-cart/', views.ClearCartView.as_view(), name='clear_cart'),
    path('cart/remove/<int:pk>/', views.RemoveFromCartView.as_view(), name='remove_from_cart'),
    path('cart/update_cart_quantity/<int:item_id>/', views.UpdateCartQuantityView.as_view(), name='update_cart_quantity'),
    path('payment_complete/', views.PaymentCompleteView.as_view(), name='payment_complete'),
    
    
    path('order-history-image/<int:order_history_id>/', views.OrderHistoryImageView.as_view(), name='order_history_image'),

    
    path('order-history/', views.OrderHistoryView.as_view(), name='order_history'),
    path('order-history/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    
    # path('save-address/', views.SaveAddressView.as_view(), name='save_address'),  # Define the URL pattern for save_address
    # path('confirm-address/', views.ConfirmAddressView.as_view(), name='confirm_address'),
    path('confirm-address/', views.confirm_address, name='confirm_address'),
    path('pay-with-paypal/', views.pay_with_paypal, name='pay_with_paypal'),
    
    path('paypal/', include('paypal.standard.ipn.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from django.shortcuts import render 
from . import views
from django.conf import settings

app_name = 'products'

urlpatterns = [
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('products/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    
    


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from django.shortcuts import render 
from . import views
from django.conf import settings

app_name = 'userprofile'

urlpatterns = [
    # Authentication
    path('sign-in/', views.SignInView.as_view(), name='sign_in'),
    path('signup/', views.signup, name='signup'),
    path('check-username/', views.check_username_availability, name='check_username_availability'),
    path('check-email/', views.check_email_availability, name='check_email_availability'),
    
    path('logout/', views.LogoutView.as_view(), name='logout'),
    
    # Profile
    path('profile/', views.ProfileView.as_view(), name='profile'),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/views.py
from multiprocessing import AuthenticationError
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import logout
from django.views.generic import ListView
from products.models import *
from django.shortcuts import render, get_object_or_404
from orders.models import *
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView


# If user is not logged in, show home.html
class HomeView(TemplateView):
    template_name = 'home/home.html'

# class BaseView(LoginRequiredMixin, TemplateView):
#     template_name = 'base.html'

# If user is logged in, show home_auth.html
class HomeAuth(LoginRequiredMixin, TemplateView):
    def get(self, request):
        template = 'home/home_auth.html'
        return render(request, template)
    

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block meta %}

    {% endblock meta %}
    <link rel="stylesheet" href="{% static 'css/bootstrap/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/sweetalert/all.min.css' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
        integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/home/base.css' %}">
    {% block css %}{% endblock %}
    <title>{% block title %}Home{% endblock %}</title>

    <script src="{% static 'js/bootstrap/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/sweetalert/sweetalert2@11.js' %}"></script>
    <script src="{% static 'js/carts/cartAuth.js' %}"></script>




</head>

<body>
    <!-- navbar start -->
    <nav class="navbar navbar-expand-lg fixed-top">
        <div class="container">
            <!-- Logo on the left -->
            <a class="navbar-brand logo-name" href="#">
                <img src="{% static 'img/logo/logo.png' %}" alt="Logo" height="50"
                    class="nav-logo">
                <h5 class="logo-name-logo">Khmer Empire Shop</h5>
            </a>
            <!-- Menu items on the right -->
            <button class="navbar-toggler btn-toggle" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="40" viewBox="0,0,256,256"
                    style="fill:#000000;">
                    <g fill="#ffffff" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt"
                        stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0"
                        font-family="none" font-weight="none" font-size="none" text-anchor="none"
                        style="mix-blend-mode: normal">
                        <g transform="scale(5.12,5.12)">
                            <path
                                d="M5,8c-0.72127,-0.0102 -1.39216,0.36875 -1.75578,0.99175c-0.36361,0.623 -0.36361,1.39351 0,2.01651c0.36361,0.623 1.0345,1.00195 1.75578,0.99175h40c0.72127,0.0102 1.39216,-0.36875 1.75578,-0.99175c0.36361,-0.623 0.36361,-1.39351 0,-2.01651c-0.36361,-0.623 -1.0345,-1.00195 -1.75578,-0.99175zM5,23c-0.72127,-0.0102 -1.39216,0.36875 -1.75578,0.99175c-0.36361,0.623 -0.36361,1.39351 0,2.01651c0.36361,0.623 1.0345,1.00195 1.75578,0.99175h40c0.72127,0.0102 1.39216,-0.36875 1.75578,-0.99175c0.36361,-0.623 0.36361,-1.39351 0,-2.01651c-0.36361,-0.623 -1.0345,-1.00195 -1.75578,-0.99175zM5,38c-0.72127,-0.0102 -1.39216,0.36875 -1.75578,0.99175c-0.36361,0.623 -0.36361,1.39351 0,2.01651c0.36361,0.623 1.0345,1.00195 1.75578,0.99175h40c0.72127,0.0102 1.39216,-0.36875 1.75578,-0.99175c0.36361,-0.623 0.36361,-1.39351 0,-2.01651c-0.36361,-0.623 -1.0345,-1.00195 -1.75578,-0.99175z">
                            </path>
                        </g>
                    </g>
                </svg>
                <span class="navbar-toggler-icon"> </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active menu">
                        <a class="nav-link"
                            href="{% if user.is_authenticated %}{% url 'home:home_auth' %}{% else %}{% url 'home:home' %}{% endif %}">Home
                        </a>
                    </li>
                    <li class="nav-item menu">
                        <a class="nav-link" href="{% url 'products:product_list' %}">Product</a>
                    </li>

                    <li class="nav-item menu">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                    <li class="nav-item menu">
                        <a class="nav-link about-us" href="">About us</a>
                    </li>
                    <li class="nav cart">
                        <a class="nav-link" href="{% url 'orders:cart_detail' %}"><i
                                class="fa-solid fa-cart-shopping"></i></a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item menu">
                        <a class="nav-link user" href="{% url 'userprofile:profile' %}">{{ user.username }}</a>
                    </li>
                    <li class="nav-item menu">
                        <a class="nav-link" href="{% url 'userprofile:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item menu">
                        <a class="nav-link nav-sign-in" href="{% url 'userprofile:sign_in' %}">Sign In</a>
                    </li>
                    <li class="nav-item menu">
                        <a class="nav-link  nav-sign-up" href="{% url 'userprofile:signup' %}">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- navbar end -->
    <div class="nav-top"></div>
    {% block content %}


    {% endblock content %}

    <!-- Footer  start-->
    <footer>
        <div class="footer">
            <img src="https://cdn-icons-png.flaticon.com/512/1354/1354444.png" alt="Logo" height="120"
                class="footer-logo">
            <h2>Khmer Empire Shop</h2>
            <div class="social-icons">
                <a href="https://facebook.com" class="logo-social-media"><i class="fa-brands fa-facebook"></i></a>
                <a href="https://twitter.com" class="logo-social-media"><i class="fa-brands fa-x-twitter"></i></a>
                <a href="https://youtube.com" class="logo-social-media" <i class="fa-brands fa-youtube"></i></a>
                <a href="https://telegram.com" class="logo-social-media"><i class="fa-brands fa-telegram"></i></a>
            </div>
            <p>Contact: +855 888026678</p>
            <p class="copy-rigth">&copy; 2023 Khmer Empire Computer Shop. All rights reserved.</p>
        </div>
    </footer>
    <!-- Footer end -->
    {% block js %}

    {% endblock js %}


</body>

</html>