KhmerEmpireShop/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('products.urls')),
    path('', include('userprofile.urls')),
    path('', include('orders.urls')),
    path('', include('dashboard.urls')),
    path('', include('api.urls')),
    
    
    
    
    path('accounts/', include('allauth.urls')),
    
    
]

api/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from django.shortcuts import render 
from . import views
from django.conf import settings


urlpatterns = [
    path('api/products/', views.LaptopSpecListAPI.as_view(), name='products-api'),
    path('api/products/<slug:slug>/', views.ProductDetailBySlugAPI.as_view(), name='product-detail-api'),
    




    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from django.shortcuts import render 
from . import views
from django.conf import settings

app_name = 'dashboard'

urlpatterns = [
    # path('base/', views.base, name='base'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('dashboard/sign_in/', views.DashboardSignInView.as_view(), name='sign_in'),
    path('dashboard/logout/', views.DashboardLogoutView.as_view(), name='logout'),
    
    
    path('dashboard/order/', views.OrderHistoryView.as_view(), name='order'),
    path('dashboard/order/<int:pk>/update_status/', views.OrderStatusUpdateView.as_view(), name='order_status_update'),

    
    path('dashboard/products/', views.ProductListView.as_view(), name='product_list'),
    path('dashboard/products/add/', views.ProductCreateView.as_view(), name='product_add'),
    path('products/edit/<int:pk>/', views.ProductUpdateView.as_view(), name='product_edit'),
    path('products/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product_delete'),
    # path('delete-product-image/<int:image_id>/', views.DeleteProductImageView.as_view(), name='delete_product_image'),
    
    path('dashboard/order/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    
    path('dashboard/tables/', views.DisplayTablesView.as_view(), name='display_tables'),
    path('dashboard/edit/<str:model>/<int:pk>/', views.EditModelView.as_view(), name='edit_model'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from products.models import *
from django.forms.widgets import FileInput
from django.forms import inlineformset_factory

class MultipleFileInput(FileInput):
    def __init__(self, attrs=None):
        super().__init__(attrs)
        if attrs is None:
            attrs = {}
        attrs.update({'multiple': 'multiple'})
        self.attrs = attrs

class LaptopSpecForm(forms.ModelForm):
    class Meta:
        model = LaptopSpec
        fields = [
            'cpu', 'gpu', 'memory', 'storage', 'display', 'webcam',
            'battery', 'weight', 'operating_system', 'port', 'wireless_connectivity'
        ]
        widgets = {
            'cpu': forms.Select(attrs={'class': 'form-control'}),
            'gpu': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'memory': forms.Select(attrs={'class': 'form-control'}),
            'storage': forms.Select(attrs={'class': 'form-control'}),
            'display': forms.Select(attrs={'class': 'form-control'}),
            'webcam': forms.Select(attrs={'class': 'form-control'}),
            'battery': forms.Select(attrs={'class': 'form-control'}),
            'weight': forms.TextInput(attrs={'class': 'form-control'}),
            'operating_system': forms.Select(attrs={'class': 'form-control'}),
            'port': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'wireless_connectivity': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }


class ProductForm(forms.ModelForm):
    images = forms.FileField(widget=MultipleFileInput(), required=False)

    class Meta:
        model = Product
        exclude = ['slug', 'cpu', 'gpu', 'memory', 'storage', 'display', 'port', 'wireless_connectivity', 'webcam', 'battery', 'operating_system']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        instance = super(ProductForm, self).save(commit=False)
        if commit:
            instance.save()
            images = self.files.getlist('images')
            for image in images:
                ProductImage.objects.create(product=instance, image=image)
        return instance

LaptopSpecFormSet = inlineformset_factory(
    Product, LaptopSpec, form=LaptopSpecForm, extra=1, can_delete=False
)

dashboard/views.py
import json
from django.shortcuts import get_object_or_404, render
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.shortcuts import redirect
from django.contrib.auth import logout
from products.models import *
from orders.models import *
from datetime import date, timedelta
from django.views.generic import ListView, DetailView
from .mixins import SuperuserRequiredMixin
from django.db.models import Sum
from django.http import HttpResponse
import io
from bokeh.plotting import figure
from bokeh.embed import components
from plotly.offline import plot
import plotly.graph_objs as go
from userprofile.models import *
from .forms import *
from django.contrib import messages
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect, HttpResponseForbidden







# Create your views here.

class DashboardView(LoginRequiredMixin, SuperuserRequiredMixin, TemplateView):
    template_name = 'dashboard/dashboard.html'
    login_url = reverse_lazy('dashboard:sign_in')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_products'] = Product.objects.count()
        context['total_orders'] = OrderHistory.objects.count()
        context['total_users'] = User.objects.count()

        # Retrieve the newest product
        newest_product = Product.objects.latest('id')
        context['newest_product_name'] = newest_product.name
        return context

class DashboardSignInView(LoginView):
    template_name = 'dashboard/sign_in.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        else:
            return reverse_lazy('dashboard:dashboard')

class DashboardLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('dashboard:sign_in')


class OrderHistoryView(LoginRequiredMixin, SuperuserRequiredMixin, ListView):
    model = OrderHistory
    template_name = 'dashboard/orders.html'
    context_object_name = 'order_histories'
    paginate_by = 10  

    def get_queryset(self):
        # Filter the order history by the logged-in user and status
        status = self.request.GET.get('status', OrderStatus.PENDING)
        return OrderHistory.objects.filter(user=self.request.user, status=status).order_by('-ordered_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status_filter'] = self.request.GET.get('status', OrderStatus.PENDING)
        
        # Add address data for each order
        for order in context['order_histories']:
            address = Address.objects.filter(user=order.user).first()
            if address:
                order.province = address.province
            else:
                order.province = 'N/A'
                
        return context

class OrderStatusUpdateView(LoginRequiredMixin, SuperuserRequiredMixin, View):
    def post(self, request, pk):
        order_history = get_object_or_404(OrderHistory, pk=pk)
        new_status = request.POST.get('status')
        if new_status in [OrderStatus.COMPLETED, OrderStatus.CANCELLED]:
            order_history.update_status(new_status)
            messages.success(request, f'Order {order_history.id} has been updated to {new_status}')
        else:
            messages.error(request, 'Invalid status')
        return redirect('dashboard:order')


class OrderDetailView(LoginRequiredMixin, SuperuserRequiredMixin, DetailView):
    model = OrderHistory
    template_name = 'dashboard/order_detail.html'
    context_object_name = 'order'
    login_url = reverse_lazy('dashboard:sign_in')


class ProductListView(ListView, SuperuserRequiredMixin):
    model = Product
    template_name = 'dashboard/product_list.html'
    context_object_name = 'products'
    paginate_by = 10

    def get_queryset(self):
        return Product.objects.all()


class ProductCreateView(CreateView, SuperuserRequiredMixin):
    model = Product
    form_class = ProductForm
    template_name = 'dashboard/add/add_new_product.html'
    success_url = reverse_lazy('dashboard:product_list')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['laptopspec_formset'] = LaptopSpecFormSet(self.request.POST)
        else:
            data['laptopspec_formset'] = LaptopSpecFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        laptopspec_formset = context['laptopspec_formset']
        if laptopspec_formset.is_valid():
            product_instance = form.save()
            laptopspec_formset.instance = product_instance
            laptopspec_formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))

class ProductUpdateView(UpdateView, SuperuserRequiredMixin):
    model = Product
    form_class = ProductForm
    template_name = 'dashboard/edit/edit_product.html'
    success_url = reverse_lazy('dashboard:product_list')

    def get_context_data(self, **kwargs):
        data = super(ProductUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['laptopspec_formset'] = LaptopSpecFormSet(self.request.POST, instance=self.object)
        else:
            data['laptopspec_formset'] = LaptopSpecFormSet(instance=self.object)
        data['product'] = self.object  # Ensure the product instance is added to context
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        laptopspec_formset = context['laptopspec_formset']
        if laptopspec_formset.is_valid():
            response = super().form_valid(form)
            laptopspec_formset.instance = self.object
            laptopspec_formset.save()
            return response
        else:
            return self.form_invalid(form)



class ProductDeleteView(DeleteView, SuperuserRequiredMixin):
    model = Product
    success_url = reverse_lazy('dashboard:product_list')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponseRedirect(self.success_url)

class DisplayTablesView(TemplateView):
    template_name = 'dashboard/table/tables.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Get instances of all models except LaptopSpec and Product
        context['categories'] = Category.objects.all()
        context['brands'] = Brand.objects.all()
        context['colors'] = Color.objects.all()
        context['cpu_brands'] = CpuBrand.objects.all()
        context['gpu_brands'] = GpuBrand.objects.all()
        context['cpu_specs'] = CpuSpec.objects.all()
        context['gpu_specs'] = GpuSpec.objects.all()
        context['memory_brands'] = MemoryBrand.objects.all()
        context['memory_specs'] = MemorySpec.objects.all()
        context['storage_brands'] = StorageBrand.objects.all()
        context['storage_specs'] = StorageSpec.objects.all()
        context['display_specs'] = DisplaySpec.objects.all()
        context['port_specs'] = PortSpec.objects.all()
        context['wireless_connectivities'] = WirelessConnectivity.objects.all()
        context['webcam_specs'] = WebcamSpec.objects.all()
        context['battery_specs'] = BatterySpec.objects.all()
        context['operating_systems'] = OperatingSystem.objects.all()
        return context


class EditModelView(UpdateView):
    template_name = 'dashboard/edit/edit_model.html'
    model = None
    fields = '__all__'
    success_url = reverse_lazy('dashboard:display_tables')

    def get_object(self, queryset=None):
        model_name = self.kwargs.get('model')
        if model_name == 'category':
            self.model = Category
        elif model_name == 'brand':
            self.model = Brand
        elif model_name == 'color':
            self.model = Color
        elif model_name == 'cpu_brand':
            self.model = CpuBrand
        elif model_name == 'gpu_brand':
            self.model = GpuBrand
        elif model_name == 'cpu_spec':
            self.model = CpuSpec
        elif model_name == 'gpu_spec':
            self.model = GpuSpec
        elif model_name == 'memory_brand':
            self.model = MemoryBrand
        elif model_name == 'memory_spec':
            self.model = MemorySpec
        elif model_name == 'storage_brand':
            self.model = StorageBrand
        elif model_name == 'storage_spec':
            self.model = StorageSpec
        elif model_name == 'display_spec':
            self.model = DisplaySpec
        elif model_name == 'port_spec':
            self.model = PortSpec
        elif model_name == 'wireless_connectivity':
            self.model = WirelessConnectivity
        elif model_name == 'webcam_spec':
            self.model = WebcamSpec
        elif model_name == 'battery_spec':
            self.model = BatterySpec
        elif model_name == 'operating_system':
            self.model = OperatingSystem
        return super().get_object(queryset)

    def get_form_class(self):
        form_class = super().get_form_class()
        if hasattr(self.model, 'slug'):
            fields = form_class.Meta.fields
            fields = [field for field in fields if field != 'slug']
            form_class.Meta.fields = fields
        return form_class

dashboard/templates/dashboard/table/battery.html
<h2>Battery</h2>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Action</th>
    </tr>
    {% for battery_spec in battery_specs %}
    <tr>
        <td>{{ battery_spec.battery }} Kwh</td>
        <td><a href="{% url 'dashboard:edit_model' model='battery_spec' pk=battery_spec.pk %}">Edit</a> | <a href="">Delete</a></td>

        </td>
    </tr>
    {% endfor %}
</table>

dashboard/templates/dashboard/table/brand.html
<h2>Brands</h2>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Edit/Delete</th>
    </tr>
    {% for brand in brands %}
    <tr>
        <td>{{ brand.name }}</td>
        <td><a href="">Edit</a> | <a href="">Delete</a>
        </td>
    </tr>
    {% endfor %}
</table>

dashboard/templates/dashboard/table/category.html
<h2>Category</h2>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Edit/Delete</th>
    </tr>
    {% for category in categories %}
    <tr>
        <td>{{ category.name }}</td>
        <td><a href=""">Edit</a> | <a
                href="">Delete</a></td>
    </tr>
    {% endfor %}
</table>

dashboard/templates/dashboard/table/color.html
<h2>Color</h2>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Edit/Delete</th>
    </tr>
    {% for color in colors %}
    <tr>
        <td>{{ color.name }}</td>
        <td><a href="">Edit</a> | <a href="">Delete</a>
        </td>
    </tr>
    {% endfor %}
</table>

dashboard/templates/dashboard/table/display.html
<h2>Display</h2>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Action</th>
    </tr>
    {% for display_spec in display_specs %}
    <tr>
        <td>{{ display_spec.display }} Inches</td>
        <td><a href="{% url 'dashboard:edit_model' model='display_spec' pk=display_spec.pk %}">Edit</a> | <a href="">Delete</a></td>

        </td>
    </tr>
    {% endfor %}
</table>

dashboard/templates/dashboard/table/operating_system.html
<h2>Operating System</h2>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Action</th>
    </tr>
    {% for operating_system in operating_systems %}
    <tr>
        <td>{{ operating_system.operating_system }}</td>
        <td><a href="{% url 'dashboard:edit_model' model='operating_system' pk=operating_system.pk %}">Edit</a> | <a href="">Delete</a></td>
    </tr>
    {% endfor %}
</table>

dashboard/templates/dashboard/table/port.html
<h2>Port</h2>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Action</th>
    </tr>
    {% for port_spec in port_specs %}
    <tr>
        <td>{{ port_spec.port }}</td>
        <td><a href="{% url 'dashboard:edit_model' model='port_spec' pk=port_spec.pk %}">Edit</a> | <a href="">Delete</a></td>

        </td>
    </tr>
    {% endfor %}
</table>

dashboard/templates/dashboard/table/tables.html
{% extends 'dashboard_base.html' %}

{% block content %}
<style>
    .collapsible {
        background-color: #28282b;
        border-radius: 15px;
        color: white;
        cursor: pointer;
        padding: 18px;
        width: 100%;
        border: none;
        text-align: left;
        outline: none;
        font-size: 15px;
        transition: background-color 0.5s ease-in-out; /* Add transition for background color */
    }
    
    .active, .collapsible:hover {
        background-color: #555;
    }
    
    .content {
        max-height: 0;
        overflow: hidden;
        transition: max-height 0.5s ease-in-out; /* Add transition for max-height */
    }
    
    .collapsible.active + .content {
        max-height: 1000px; /* Set a value larger than the expected maximum height of the content */
    }
    
    .row {
        margin-bottom: 20px;
    }
    
</style><div class="container">
    <h1>Table</h1>
    <div class="row">
        <div class="col-md-4">
            <button class="collapsible">Category</button>
            <div class="content">
                {% include 'dashboard/table/category.html' %}
            </div>
        </div>
        <div class="col-md-4">
            <button class="collapsible">Brand</button>
            <div class="content">
                {% include 'dashboard/table/brand.html' %}
            </div>
        </div>
        <div class="col-md-4">
            <button class="collapsible">Color</button>
            <div class="content">
                {% include 'dashboard/table/color.html' %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <button class="collapsible">CPU Brand</button>
            <div class="content">
                {% include 'dashboard/table/cpu/cpu_brand.html' %}
            </div>
        </div>
        <div class="col-md-4">
            <button class="collapsible">CPU</button>
            <div class="content">
                {% include 'dashboard/table/cpu/cpu.html' %}
            </div>
        </div>
        <div class="col-md-4">
            <button class="collapsible">GPU Brand</button>
            <div class="content">
                {% include 'dashboard/table/gpu/gpu_brand.html' %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <button class="collapsible">GPU</button>
            <div class="content">
                {% include 'dashboard/table/gpu/gpu.html' %}
            </div>
        </div>
        <div class="col-md-4">
            <button class="collapsible">Memory Brand</button>
            <div class="content">
                {% include 'dashboard/table/memory/memory_brand.html' %}
            </div>
        </div>
        <div class="col-md-4">
            <button class="collapsible">Memory</button>
            <div class="content">
                {% include 'dashboard/table/memory/memory.html' %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <button class="collapsible">Storage Brand</button>
            <div class="content">
                {% include 'dashboard/table/storage/storage_brand.html' %}
            </div>
        </div>
        <div class="col-md-4">
            <button class="collapsible">Storage</button>
            <div class="content">
                {% include 'dashboard/table/storage/storage.html' %}
            </div>
        </div>
        <div class="col-md-4">
            <button class="collapsible">Display</button>
            <div class="content">
                {% include 'dashboard/table/display.html' %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <button class="collapsible">Port</button>
            <div class="content">
                {% include 'dashboard/table/port.html' %}
            </div>
        </div>
        <div class="col-md-4">
            <button class="collapsible">Wireless Connectivity</button>
            <div class="content">
                {% include 'dashboard/table/wireless_connectivity.html' %}
            </div>
        </div>
        <div class="col-md-4">
            <button class="collapsible">Webcam</button>
            <div class="content">
                {% include 'dashboard/table/webcam.html' %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <button class="collapsible">Battery</button>
            <div class="content">
                {% include 'dashboard/table/battery.html' %}
            </div>
        </div>
        <div class="col-md-4">
            <button class="collapsible">Operating System</button>
            <div class="content">
                {% include 'dashboard/table/operating_system.html' %}
            </div>
        </div>
    </div>
</div>
<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
        coll[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.display === "block") {
                content.style.display = "none";
            } else {
                content.style.display = "block";
            }
        });
    }
</script>

{% endblock content %}

dashboard/templates/dashboard/table/webcam.html
<h2>Webcam</h2>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Action</th>
    </tr>
    {% for webcam_spec in webcam_specs %}
    <tr>
        <td>{{ webcam_spec.webcam }}</td>
        <td><a href="{% url 'dashboard:edit_model' model='webcam_spec' pk=webcam_spec.pk %}">Edit</a> | <a href="">Delete</a></td>

        </td>
    </tr>
    {% endfor %}
</table>

dashboard/templates/dashboard/table/wireless_connectivity.html
<h2>Wireless Connectivity</h2>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Action</th>
    </tr>
    {% for wireless_connectivity in wireless_connectivities %}
    <tr>
        <td>{{ wireless_connectivity.wireless_connectivity }}</td>
        <td><a href="{% url 'dashboard:edit_model' model='wireless_connectivity' pk=wireless_connectivity.pk %}">Edit</a> | <a href="">Delete</a></td>

        </td>
    </tr>
    {% endfor %}
</table>