KhmerEmpireShop/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('products.urls')),
    path('', include('userprofile.urls')),
    path('', include('orders.urls')),
    path('', include('dashboard.urls')),
    path('', include('api.urls')),
    
    
    
    
    path('accounts/', include('allauth.urls')),
    
    
]

api/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from django.shortcuts import render 
from . import views
from django.conf import settings


urlpatterns = [
    path('api/products/', views.LaptopSpecListAPI.as_view(), name='products-api'),
    path('api/products/<slug:slug>/', views.ProductDetailBySlugAPI.as_view(), name='product-detail-api'),
    




    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from django.shortcuts import render 
from . import views
from django.conf import settings

app_name = 'dashboard'

urlpatterns = [
    # path('base/', views.base, name='base'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('dashboard/sign_in/', views.DashboardSignInView.as_view(), name='sign_in'),
    path('dashboard/logout/', views.DashboardLogoutView.as_view(), name='logout'),
    
    
    path('dashboard/order/', views.OrderHistoryView.as_view(), name='order'),
    path('dashboard/order/<int:pk>/update_status/', views.OrderStatusUpdateView.as_view(), name='order_status_update'),

    
    path('dashboard/products/', views.ProductListView.as_view(), name='product_list'),
    path('dashboard/products/add/', views.ProductCreateView.as_view(), name='product_add'),
    path('products/edit/<int:pk>/', views.ProductUpdateView.as_view(), name='product_edit'),
    path('products/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product_delete'),
    # path('delete-product-image/<int:image_id>/', views.DeleteProductImageView.as_view(), name='delete_product_image'),
    
    path('dashboard/order/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    
    path('dashboard/tables/', views.DisplayTablesView.as_view(), name='display_tables'),
    path('dashboard/edit/<str:model>/<int:pk>/', views.EditModelView.as_view(), name='edit_model'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from django.shortcuts import render 
from . import views
from django.conf import settings

app_name = 'orders'

urlpatterns = [
    path('check-login-status/', views.CheckLoginStatusView.as_view(), name='check_login_status'),
    path('add-to-cart/<slug:slug>/',views. AddToCartView.as_view(), name='add_to_cart'),
    path('cart/', views.CartDetailView.as_view(), name='cart_detail'),
    path('clear-cart/', views.ClearCartView.as_view(), name='clear_cart'),
    path('cart/remove/<int:pk>/', views.RemoveFromCartView.as_view(), name='remove_from_cart'),
    path('cart/update_cart_quantity/<int:item_id>/', views.UpdateCartQuantityView.as_view(), name='update_cart_quantity'),
    path('payment_complete/', views.PaymentCompleteView.as_view(), name='payment_complete'),
    
    
    path('order-history-image/<int:order_history_id>/', views.OrderHistoryImageView.as_view(), name='order_history_image'),

    
    path('order-history/', views.OrderHistoryView.as_view(), name='order_history'),
    path('order-history/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    
    # path('save-address/', views.SaveAddressView.as_view(), name='save_address'),  # Define the URL pattern for save_address
    # path('confirm-address/', views.ConfirmAddressView.as_view(), name='confirm_address'),
    path('confirm-address/', views.confirm_address, name='confirm_address'),
    path('pay-with-paypal/', views.pay_with_paypal, name='pay_with_paypal'),
    
    path('paypal/', include('paypal.standard.ipn.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

orders/models.py
from fileinput import filename
from typing_extensions import Buffer
from django.db import models
from products.models import *
from io import BytesIO
from django.core.files import File
from PIL import Image
import qrcode
from django.urls import reverse
from decimal import Decimal

# Create your models here.

class OrderStatus(models.TextChoices):
    PENDING = 'Pending', 'Pending'
    COMPLETED = 'Completed', 'Completed'
    CANCELLED = 'Cancelled', 'Cancelled'

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    # status = models.CharField(max_length=20, choices=OrderStatus.choices, default=OrderStatus.PENDING)

    def calculate_total_price(self):
        # Calculate total price based on cart items
        total = Decimal(0)
        for item in self.cartitem_set.all():
            total += item.subtotal
        self.total_price = total
        self.save()
        
    def __str__(self):
        return f"Order #{self.id} - Total: ${self.total_price:.2f}"

class CartItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

    def __str__(self):
        return f"CartItem #{self.id} - {self.product} - Quantity: {self.quantity} - Subtotal: ${self.subtotal:.2f}"

    def save(self, *args, **kwargs):
        self.subtotal = self.product.price * self.quantity
        super().save(*args, **kwargs)
        order_items = self.order.cartitem_set.all()
        self.order.total_price = sum(item.subtotal for item in order_items)
        self.order.save()

class OrderHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered_date = models.DateTimeField(default=timezone.now)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    status = models.CharField(max_length=20, choices=OrderStatus.choices, default=OrderStatus.PENDING)
    qr_code = models.ImageField(upload_to='qr_codes', blank=True, null=True)

    def __str__(self):
        return f"Order History #{self.id} - {self.ordered_date} - Total: ${self.total_price:.2f}"

    def update_status(self, new_status):
        if new_status in [OrderStatus.COMPLETED, OrderStatus.CANCELLED]:
            self.status = new_status
            self.save()
            
    def generate_qr_code(self, request):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        
        # Construct the full URL with the request object
        host = request.get_host()
        qr_data = f'http://{host}{reverse("orders:order_history_image", args=[self.id])}'
        qr.add_data(qr_data)
        qr.make(fit=True)

        img = qr.make_image(fill='black', back_color='white')
        buffer = BytesIO()
        img.save(buffer, 'PNG')
        buffer.seek(0)  # Ensure the pointer is at the start of the buffer

        # Save the QR code image to the qr_code field
        file_name = f'order_{self.id}_qr.png'
        self.qr_code.save(file_name, File(buffer), save=True)


class OrderHistoryItem(models.Model):
    order_history = models.ForeignKey(OrderHistory, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)

    def product_details(self):
        return f"{self.product.brand_name} - {self.product.description}"

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

CAMBODIAN_PROVINCES = [
    ('Banteay Meanchey', 'Banteay Meanchey'),
    ('Battambang', 'Battambang'),
    ('Kampong Cham', 'Kampong Cham'),
    ('Kampong Chhnang', 'Kampong Chhnang'),
    ('Kampong Speu', 'Kampong Speu'),
    ('Kampong Thom', 'Kampong Thom'),
    ('Kampot', 'Kampot'),
    ('Kandal', 'Kandal'),
    ('Koh Kong', 'Koh Kong'),
    ('Kratie', 'Kratie'),
    ('Mondulkiri', 'Mondulkiri'),
    ('Phnom Penh', 'Phnom Penh'),
    ('Preah Vihear', 'Preah Vihear'),
    ('Prey Veng', 'Prey Veng'),
    ('Pursat', 'Pursat'),
    ('Ratanakiri', 'Ratanakiri'),
    ('Siem Reap', 'Siem Reap'),
    ('Preah Sihanouk', 'Preah Sihanouk'),
    ('Stung Treng', 'Stung Treng'),
    ('Svay Rieng', 'Svay Rieng'),
    ('Takeo', 'Takeo'),
    ('Oddar Meanchey', 'Oddar Meanchey'),
    ('Kep', 'Kep'),
    ('Pailin', 'Pailin'),
    ('Tboung Khmum', 'Tboung Khmum'),
]

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address1 = models.CharField(max_length=100, null=True)
    address2 = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=50, null=True)
    province = models.CharField(max_length=50, choices=CAMBODIAN_PROVINCES, null=True)
    phone = models.CharField(max_length=20, null=True)
    address_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.address1}, {self.city}, {self.province}"

    class Meta:
        verbose_name_plural = "Addresses"



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    pfp = models.ImageField(upload_to='profile_pics', blank=True, null=True)

    def __str__(self):
        return self.user.username

dashboard/forms.py
from django import forms
from products.models import *
from django.forms.widgets import FileInput
from django.forms import inlineformset_factory

class MultipleFileInput(FileInput):
    def __init__(self, attrs=None):
        super().__init__(attrs)
        if attrs is None:
            attrs = {}
        attrs.update({'multiple': 'multiple'})
        self.attrs = attrs

class LaptopSpecForm(forms.ModelForm):
    class Meta:
        model = LaptopSpec
        fields = [
            'cpu', 'gpu', 'memory', 'storage', 'display', 'webcam',
            'battery', 'weight', 'operating_system', 'port', 'wireless_connectivity'
        ]
        widgets = {
            'cpu': forms.Select(attrs={'class': 'form-control'}),
            'gpu': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'memory': forms.Select(attrs={'class': 'form-control'}),
            'storage': forms.Select(attrs={'class': 'form-control'}),
            'display': forms.Select(attrs={'class': 'form-control'}),
            'webcam': forms.Select(attrs={'class': 'form-control'}),
            'battery': forms.Select(attrs={'class': 'form-control'}),
            'weight': forms.TextInput(attrs={'class': 'form-control'}),
            'operating_system': forms.Select(attrs={'class': 'form-control'}),
            'port': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'wireless_connectivity': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }


class ProductForm(forms.ModelForm):
    images = forms.FileField(widget=MultipleFileInput(), required=False)

    class Meta:
        model = Product
        exclude = ['slug', 'cpu', 'gpu', 'memory', 'storage', 'display', 'port', 'wireless_connectivity', 'webcam', 'battery', 'operating_system']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        instance = super(ProductForm, self).save(commit=False)
        if commit:
            instance.save()
            images = self.files.getlist('images')
            for image in images:
                ProductImage.objects.create(product=instance, image=image)
        return instance

LaptopSpecFormSet = inlineformset_factory(
    Product, LaptopSpec, form=LaptopSpecForm, extra=1, can_delete=False
)

dashboard/templates/dashboard/dashboard.html
{% extends 'dashboard_base.html' %}
{% load static %}

{% block title %}
Dashboard
{% endblock title %}
{% block content %}


<div class="row ">
    <div class="col-lg-6 col-sm-6">
        <div class="card mb-3">
            <div class="card-header p-3 pt-2">
                <div
                    class="icon icon-lg icon-shape bg-gradient-dark shadow-dark shadow text-center border-radius-xl mt-n4 position-absolute">
                    <i class="fa fa-box"></i>
                </div>
                <div class="text-end pt-1">
                    <p class="text-sm mb-0 text-capitalize">Products</p>
                    <h4 class="mb-0">{{ total_products }}</h4>
                </div>
            </div>

            <hr class="dark horizontal my-0">
            <div class="card-footer p-3">
                <p class="mb-0"><span class="text-success text-sm font-weight-bolder">+55% </span>than last week</p>
            </div>
        </div>

        <div class="card mb-2">
            <div class="card-header p-3 pt-2">
                <div
                    class="icon icon-lg icon-shape bg-gradient-primary shadow-primary shadow text-center border-radius-xl mt-n4 position-absolute">
                    <i class="fa fa-circle-plus"></i>
                </div>
                <div class="text-end pt-1">
                    <p class="text-sm mb-0 text-capitalize">Newest Product</p>
                    <h4 class="mb-0">{{ newest_product_name }}</h4>
                </div>
            </div>

            <hr class="dark horizontal my-0">
            <div class="card-footer p-3">
                <p class="mb-0"><span class="text-success text-sm font-weight-bolder">+3% </span>than last month</p>
            </div>
        </div>

    </div>
    <div class="col-lg-6 col-sm-6 mt-sm-0 mt-4">
        <div class="card mb-3">
            <div class="card-header p-3 pt-2 bg-transparent">
                <div
                    class="icon icon-lg icon-shape bg-gradient-success shadow-success text-center border-radius-xl mt-n4 position-absolute">
                    <i class="fa fa-cart-shopping"></i>
                </div>
                <div class="text-end pt-1">
                    <p class="text-sm mb-0 text-capitalize ">Today's order</p>
                    <h4 class="mb-0 ">{{ total_orders }}</h4>
                </div>
            </div>

            <hr class="horizontal my-0 dark">
            <div class="card-footer p-3">
                <p class="mb-0 "><span class="text-success text-sm font-weight-bolder">+1% </span>than yesterday</p>
            </div>
        </div>

        <div class="card">
            <div class="card-header p-3 pt-2 bg-transparent">
                <div
                    class="icon icon-lg icon-shape bg-gradient-info shadow-info text-center border-radius-xl mt-n4 position-absolute">
                    <i class="fa fa-user"></i>
                </div>
                <div class="text-end pt-1">
                    <p class="text-sm mb-0 text-capitalize">Total Users</p>
                    <h4 class="mb-0">{{ total_users }}</h4>
                </div>
            </div>

            <hr class="horizontal my-0 dark">
            <div class="card-footer p-3">
                <p class="mb-0">Just updated</p>
            </div>
        </div>


    </div>
        <div class="row">
            <div class="col-md-6">
                {% include 'dashboard/most_order.html' %}

            </div>
        </div>

    </div>

    {% endblock content %}

    {% block js %}
    <script src="{% static 'js/bootstrap/material-dashboard.min.js' %}"></script>
    {% endblock js %}

dashboard/templates/dashboard/order_detail.html
{% extends "dashboard_base.html" %}

{% block content %}
<a href="{% url 'dashboard:order' %}" class="btn btn-secondary"><i class="fa fa-backward"></i></a>

<div class="container">
<h2>Order Detail</h2>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <table class="table">
                <tr>
                    <th>Order ID</th>
                    <td><span class="font-weight-bold">#{{ order.id }}</span></td>
                </tr>
                <tr>
                    <th>Ordered Date</th>
                    <td>{{ order.ordered_date }}</td>
                </tr>
                <tr>
                    <th>Total Price</th>
                    <td><span class="text-danger font-weight-bold">${{ order.total_price }}</span></td>
                </tr>
                <tr>
                    <th>Status</th>
                    <td>
                        {% if order.status == 'Pending' %}
                            <span class="badge bg-warning">{{ order.get_status_display }}</span>
                        {% elif order.status == 'Completed' %}
                            <span class="badge bg-success">{{ order.get_status_display }}</span>
                        {% elif order.status == 'Cancelled' %}
                            <span class="badge bg-danger">{{ order.get_status_display }}</span>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th>Ordered By</th>
                    <td>{{ order.user.username }}</td>
                </tr>
            </table>
        </div>
        <div class="col-md-6">
            <table class="table">
                <tr>
                    <th>Address</th>
                    <td>
                        {% with address=order.user.address_set.first %}
                            {% if address %}
                                Address 1: {{ address.address1 }}<br> 
                                Address 2: {{ address.address2 }}<br> 
                                City: {{ address.city }}<br>
                                Province: {{ address.province }}<br>
                                Phone number: {{ address.phone }}
                            {% else %}
                                N/A
                            {% endif %}
                        {% endwith %}
                    </td>
                </tr>
                <tr>
                    <th>QR Code</th>
                    <td>
                        {% if order.qr_code %}
                        <img src="{{ order.qr_code.url }}" alt="QR Code" width="100" height="100">
                        {% else %}
                        N/A
                        {% endif %}
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>


<h3>Order Items</h3>
<table class="table">
    <thead>
        <tr>
            <th>Product</th>
            <th>Image</th>
            <th>Quantity</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        {% for item in order.orderhistoryitem_set.all %}
        <tr>
            <td>{{ item.product.name }} {{ item.product.model }} {{ item.product.year }}</td>
            <td> {% if item.product.images.all %}
                {% with first_image=item.product.images.first %}
                <img src="{{ first_image.image.url }}" alt="{{ item.product.name }}" width="120">
                {% endwith %}
                {% else %}
               <p>no image</p>
                {% endif %}</td>
            <td>{{ item.quantity }}</td>
            <td>${{ item.subtotal }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}

dashboard/templates/dashboard/orders.html
{% extends 'dashboard_base.html' %}
{% load static %}
{% block title %}
Order
{% endblock title %}

{% block content %}



<div class="container">
    <h2>Order History</h2>
    <div class="status-buttons">
        <a href="{% url 'dashboard:order' %}?status=Pending"
            class="btn {% if status_filter == 'Pending' %}btn-warning{% else %}btn-secondary{% endif %}">Pending</a>
        <a href="{% url 'dashboard:order' %}?status=Completed"
            class="btn {% if status_filter == 'Completed' %}btn-success{% else %}btn-secondary{% endif %}">Completed</a>
        <a href="{% url 'dashboard:order' %}?status=Cancelled"
            class="btn {% if status_filter == 'Cancelled' %}btn-danger{% else %}btn-secondary{% endif %}">Cancelled</a>
    </div>

</div>
<!-- Order history table -->
<!-- Order history table -->
<table class="container">
    <thead>
        <tr>
            <th>Order ID</th>
            <th>Ordered Date</th>
            <th>Total Price</th>
            <th>From</th>
            <th>Status</th>
            <th>QR Code</th>
            {% if order_histories and order_histories.0.status == "Pending" %}
                <th>Action</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for order in order_histories %}
        <tr class="clickable-row" data-href="{% url 'dashboard:order_detail' order.id %}">
            <td>#{{ order.id }}</td>
            <td>{{ order.ordered_date }}</td>
            <td>${{ order.total_price }}</td>
            <td>{{ order.province }}</td>
            <td>{{ order.get_status_display }}</td>
            <td>
                {% if order.qr_code %}
                <img src="{{ order.qr_code.url }}" alt="QR Code" width="60" class="img-fluid">
                {% endif %}
            </td>
            {% if order.status == "Pending" %}
                <td>
                    <form method="post" action="{% url 'dashboard:order_status_update' order.pk %}" style="display:inline;">
                        {% csrf_token %}
                        <input type="hidden" name="status" value="Completed">
                        <button type="submit" class="btn btn-success btn-sm"><i class="fa fa-check"></i></button>
                    </form>
                    <form method="post" action="{% url 'dashboard:order_status_update' order.pk %}" style="display:inline;">
                        {% csrf_token %}
                        <input type="hidden" name="status" value="Cancelled">
                        <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-x"></i></button>
                    </form>
                </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>


<!-- Pagination controls -->
<div class="container mt-3">
    {% if is_paginated %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a href="?page=1" class="btn btn-primary">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-primary">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endif %}

{% endblock content %}

{% block js %}
<script src="{% static 'js/dashboard/Order.js' %}"></script>
{% endblock js %}

dashboard/templates/dashboard/product_list.html
{% extends "dashboard_base.html" %}

{% block content %}
<style>
    i{
        font-size: 14px !important;
    }
</style>
<div class="container">
    <h2>Product List</h2>
<a href="{% url 'dashboard:product_add' %}" class="btn btn-primary"><i class="fa fa-add"></i></a>
</div><table class="container">    
    <thead>
        <tr>
            <th>ID</th>
            <th>Product Name</th>
            <th>Model</th>
            <th>Image</th>
            <th>Brand</th>
            <th>Category</th>
            <th>Color</th>
            <th>Price</th>
            <th>Year</th>
            <th>Warranty</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for product in products %}
        <tr>
            <td>{{ product.id }}</td>
            <td>{{ product.name }}</td>
            <td>{{ product.model }}</td>
            <td>
                {% if product.images.exists %}
                    <img src="{{ product.images.first.image.url }}" alt="{{ product.name }}" width="120">
                {% else %}
                    <p>No image</p>
                {% endif %}
            </td>
            <td>{{ product.brand.name }}</td>
            <td>{{ product.category.name }}</td>
            <td>{{ product.color.name }}</td>
            <td>${{ product.price }}</td>
            <td>{{ product.year }}</td>
            <td>
                {% if product.warranty_years %}
                    {{ product.warranty_years }} year{% if product.warranty_years > 1 %}s{% endif %}
                {% endif %}
                {% if product.warranty_months %}
                    {% if product.warranty_years %} and {% endif %}
                    {{ product.warranty_months }} month{% if product.warranty_months > 1 %}s{% endif %}
                {% endif %}
            </td>
            <td>
                <a href="{% url 'dashboard:product_edit' product.id %}" class="btn btn-primary btn-sm"><i class="fa fa-pen"></i></a>
                <form method="post" action="{% url 'dashboard:product_delete' product.id %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>



<div class="pagination">
    <span class="step-links">
        {% if products.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ products.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ products.number }} of {{ products.paginator.num_pages }}.
        </span>

        {% if products.has_next %}
            <a href="?page={{ products.next_page_number }}">next</a>
            <a href="?page={{ products.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

dashboard/templates/dashboard/sign_in.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="row justify-content-center mt-5">
            
            <div class="col-md-6">
        <img src="{% static 'img/logo/logo.png' %}" alt="Logo" class="img-fluid d-block mx-auto m-3" style="width: 100px;">

                <div class="card">
                    <div class="card-header">
                        <h2 class="text-center">Sign In</h2>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3 center-input">
                                <label for="id_username" class="form-label">Username:</label>
                                <input type="text" id="id_username" name="username" class="form-control mx-auto">
                            </div>
                            <div class="mb-3 center-input">
                                <label for="id_password" class="form-label">Password:</label>
                                <input type="password" id="id_password" name="password" class="form-control mx-auto">
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap JS (optional, if you need JS features) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>